import { Roboto, Inter } from "next/font/google";
import '@/styles/fonts.css'
import '@/styles/colors.css'
import '@/styles/components.css'
import '@/styles/scaledUnits.css'
import '@/styles/globals.css';

import ClientProviderWrapper from "@/components/layout-wrappers/ClientProviderWrapper";


const inter = Inter({
  subsets: ["latin"],
  variable: '--font-inter',
  display: 'swap',
})

const roboto = Roboto({
  subsets: ["latin"],
  variable: '--font-roboto',
  display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fr" className={`${inter.variable} ${roboto.variable}`}>
      <body>
        <ClientProviderWrapper >
          {children}
        </ClientProviderWrapper>
      </body>
    </html>
  );
}
