import { Roboto, Inter } from "next/font/google";
import '@/styles/global/fonts.css'
import '@/styles/global/colors.css'
import '@/styles/global/components.css'
import '@/styles/global/scaledUnits.css'
import '@/styles/global/globals.css';

import ClientProviderWrapper from "@/components/layout-wrapper/ClientProviderWrapper";


const inter = Inter({
  subsets: ["latin"],
})

const roboto = Roboto({
  subsets: ["latin"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={`${inter.variable} ${roboto.className}`}>
        <ClientProviderWrapper >
          {children}
        </ClientProviderWrapper>
      </body>
    </html>
  );
}
